//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCase.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductId { get; set; }

        [Required(ErrorMessage = "ProductName is not empty")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "barCode is not empty")]
        public string barCode { get; set; }

        [Required(ErrorMessage = "Price is not empty")]
        public decimal Price { get; set; }

        public string Image { get; set; }

        public string explanation { get; set; }

        [Required(ErrorMessage = "Piece is not empty")]
        public int Piece { get; set; }
    }
}
